# Generated by Django 4.1.3 on 2022-12-30 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zen', '0002_alter_manga_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zen.manga'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
