# Generated by Django 4.1.3 on 2022-12-30 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zen', '0003_alter_comment_content_alter_comment_manga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zen.status'),
        ),
    ]
